import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar
            links={[
              { href: "/", text: "Home" },
              // { href: "/login", text: "Login" },
              { href: "/register", text: "Register" },
              { href: "/events", text: "Events" },
              { href: "/events/create", text: "Create Event" },
            ]}
          />
        </ThemeProvider>
        {children}
      </body>
    </html>
  );
}
